name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build (no features enabled)
      run: cargo build --verbose --release

    - name: Build (all features enabled)
      run: cargo build --verbose --all-features --release

    - name: Check semver compatibility (russh)
      uses: obi1kenobi/cargo-semver-checks-action@v2
      with:
        package: russh

    - name: Debug - Print current directory
      run: pwd

    - name: Debug - List current directory
      run: ls -la

    - name: Debug - List entire target directory
      run: ls -R target

    - name: Debug - List release directory
      run: ls -la target/release

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: russh-Linux
        path: |
          target/release/russh*
          target/release/librussh*.so
        if-no-files-found: warn

  Formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install rustfmt
      run: rustup component add rustfmt

    - name: rustfmt
      run: cargo fmt --check

  Clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Clippy
      run: rustup component add clippy

    - name: Clippy (no features enabled)
      run: cargo clippy -- -D warnings

    - name: Clippy (all features enabled)
      run: cargo clippy --all-features -- -D warnings
